### PR TITLE
Production bundle for Node server apps

### PR DESCRIPTION
**Pull request by broosk1993**
Added Babel to transpile the source code to commonjs so that other Node Server apps can use it.

### CODE REVIEW

**Comment by broosk1993** [comment]
Added MD

**Comment by layik** [comment]
Great work kake gyan, let me know when you are ready so I can merge it. Will have a quick look not anything thorough as I trust your code.

**Comment by broosk1993** [comment]
> Great work kake gyan, let me know when you are ready so I can merge it. Will have a quick look not anything thorough as I trust your code.

Thank you very much kaka Layik. I will make changes as we go. I actually wanted to discuss some issues with you. I will open an issue for that matter if that suits you.

Thanks again for the great library. It really makes our lives easier at the Department.

**Comment by layik** [comment]
Merging in that case and yes feel free kake gyan.

**Pull request merged**
